import { Room, ChecklistItem } from '../types';

export const ROOM_TEMPLATES: Record<string, ChecklistItem[]> = {
  bedroom: [
    {
      id: 'br_walls',
      category: 'Walls & Ceiling',
      item: 'Paint condition',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'br_flooring',
      category: 'Flooring',
      item: 'Carpet/hardwood condition',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'br_windows',
      category: 'Windows',
      item: 'Window functionality and cleanliness',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'br_closet',
      category: 'Storage',
      item: 'Closet doors and shelving',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'br_outlets',
      category: 'Electrical',
      item: 'Outlets and light fixtures',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
  ],
  bathroom: [
    {
      id: 'br_plumbing',
      category: 'Plumbing',
      item: 'Sink, toilet, and shower/tub functionality',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'br_tiles',
      category: 'Surfaces',
      item: 'Tile and grout condition',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'br_ventilation',
      category: 'Ventilation',
      item: 'Exhaust fan functionality',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'br_fixtures',
      category: 'Fixtures',
      item: 'Towel bars, toilet paper holder',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'br_mirror',
      category: 'Accessories',
      item: 'Mirror and medicine cabinet',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
  ],
  kitchen: [
    {
      id: 'kt_appliances',
      category: 'Appliances',
      item: 'Refrigerator, stove, dishwasher functionality',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'kt_counters',
      category: 'Surfaces',
      item: 'Countertop condition',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'kt_cabinets',
      category: 'Storage',
      item: 'Cabinet doors and drawers',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'kt_sink',
      category: 'Plumbing',
      item: 'Sink and faucet functionality',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'kt_backsplash',
      category: 'Surfaces',
      item: 'Backsplash and wall condition',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
  ],
  living: [
    {
      id: 'lv_walls',
      category: 'Walls & Ceiling',
      item: 'Paint and wall condition',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'lv_flooring',
      category: 'Flooring',
      item: 'Carpet/hardwood condition',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'lv_windows',
      category: 'Windows',
      item: 'Window functionality and treatments',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'lv_lighting',
      category: 'Electrical',
      item: 'Light fixtures and outlets',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
  ],
  utility: [
    {
      id: 'ut_washer',
      category: 'Appliances',
      item: 'Washer/dryer connections',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'ut_water_heater',
      category: 'Systems',
      item: 'Water heater condition',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'ut_hvac',
      category: 'HVAC',
      item: 'Heating/cooling system',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
    {
      id: 'ut_electrical',
      category: 'Electrical',
      item: 'Circuit breaker panel',
      condition: null,
      notes: '',
      photos: [],
      requiresAction: false,
    },
  ],
};

export function generateRoomTemplate(roomType: string, roomName: string): Room {
  const checklistItems = ROOM_TEMPLATES[roomType] || ROOM_TEMPLATES.living;
  
  return {
    id: `room_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    name: roomName,
    type: roomType as any,
    checklistItems: checklistItems.map(item => ({
      ...item,
      id: `${item.id}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    })),
  };
}

export const DEFAULT_ROOMS = [
  { name: 'Living Room', type: 'living' },
  { name: 'Kitchen', type: 'kitchen' },
  { name: 'Master Bedroom', type: 'bedroom' },
  { name: 'Master Bathroom', type: 'bathroom' },
  { name: 'Guest Bedroom', type: 'bedroom' },
  { name: 'Guest Bathroom', type: 'bathroom' },
  { name: 'Utility Room', type: 'utility' },
];